# Generated by Django 4.2.5 on 2024-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0002_vote"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=30, null=True, unique=True)),
                ("description", models.TextField(max_length=100, null=True)),
                ("completed", models.BooleanField(default=False)),
            ],
        ),
    ]
