# Generated by Django 4.2.5 on 2024-07-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0003_eventlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlist",
            name="user",
            field=models.CharField(max_length=50),
        ),
    ]
